rentCar/rentCar/Controllers/Dashboard2Controller.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using rentCar.Models;

namespace rentCar.Controllers
{
    [Authorize(Roles = "Admin")]
    public class Dashboard2Controller : Controller
    {
        private RentCarDBEntities db = new RentCarDBEntities();
        ApplicationDbContext context = new ApplicationDbContext();

        // GET: Dashboard2
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();
            ApplicationUser user = context.Users.FirstOrDefault(x => x.Id == userId);

            ViewBag.User = user;
            ViewBag.paginasAsociadas = db.PAGINA.Count();
            ViewBag.VehiculosDisponibles = db.VEHICULO.Where(vehiculo => vehiculo.ESTADO == "ACTIVO").Count();
            ViewBag.VehiculosAlquilados = db.VEHICULO.Where(vehiculo => vehiculo.ESTADO == "INACTIVO").Count();
            return View();
        }
    }
}

rentCar/rentCar/Views/Dashboard2/Index.cshtml
@using Microsoft.AspNet.Identity
@using rentCar.Models

@{
    Layout = "../Shared/dashboardLayout.cshtml";
}

<div class="page-content--bgf7">
    <!-- BREADCRUMB-->
    <section class="au-breadcrumb2">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <span class="au-breadcrumb-span">You are here:</span>
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item active">
                                    @Html.ActionLink("Home", "Index", "Dashboard2")
                                </li>
                                <li class="list-inline-item seprate">
                                    <span>/</span>
                                </li>
                                <li class="list-inline-item">Dashboard</li>
                            </ul>
                        </div>
                        <form class="au-form-icon--sm" action="" method="post">
                            <input class="au-input--w300 au-input--style2" type="text" placeholder="Search for datas &amp; reports...">
                            <button class="au-btn--submit2" type="submit">
                                <i class="zmdi zmdi-search"></i>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- END BREADCRUMB-->
    <!-- WELCOME-->
    <section class="welcome p-t-10">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="title-4">
                        Bienvenido
                        <span>@Html.Raw(User.Identity.Name)!</span>
                    </h1>
                    <hr class="line-seprate">
                </div>
            </div>
        </div>
    </section>
    <!-- END WELCOME-->
    <!-- STATISTIC-->
    <section class="statistic statistic2">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="statistic__item statistic__item--green">
                        <h2 class="number">@Html.Raw(ViewBag.paginasAsociadas)</h2>
                        <span class="desc">Paginas asociadas</span>
                        <div class="icon">
                            <i class="zmdi zmdi-search-in-page"></i>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="statistic__item statistic__item--orange">
                        <h2 class="number">@Html.Raw(ViewBag.VehiculosDisponibles)</h2>
                        <span class="desc">Vehiculos disponibles</span>
                        <div class="icon">
                            <i class="zmdi zmdi-car"></i>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="statistic__item statistic__item--blue">
                        <h2 class="number">@Html.Raw(ViewBag.VehiculosAlquilados)</h2>
                        <span class="desc">Vehiculos alquilados</span>
                        <div class="icon">
                            <i class="zmdi zmdi-car-wash"></i>
                        </div>
                    </div>
                </div>        
            </div>
        </div>
    </section>
    <!-- END STATISTIC-->
    <!-- STATISTIC CHART-->
    <section class="statistic-chart">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="title-5 m-b-35">Estadisticas</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <!-- VISITAS DIARIAS-->
                    <div class="au-card m-b-30">
                        <div class="au-card-inner">
                            <h3 class="title-2 m-b-40">Single Bar Chart</h3>
                            <canvas id="singelBarChart"></canvas>
                        </div>
                    </div>
                    <!-- VISITAS DIARIAS-->
                </div>
                <div class="col-md-6 col-lg-4">
                    <!-- TOP MARCAS-->
                    <div class="top-campaign">
                        <h3 class="title-3 m-b-30">top marcas</h3>
                        <div class="table-responsive">
                            <table class="table table-top-campaign">
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                    <!-- END TOP MARCAS-->
                </div>
                <div class="col-md-6 col-lg-4">
                    <!-- CHART PERCENT-->
                    <div class="chart-percent-2">
                        <h3 class="title-3 m-b-30">chart by %</h3>
                        <div class="chart-wrap">
                            <canvas id="percent-chart2"></canvas>
                            <div id="chartjs-tooltip">
                                <table></table>
                            </div>
                        </div>
                        <div class="chart-info">
                            <div class="chart-note">
                                <span class="dot dot--blue"></span>
                                <span>products</span>
                            </div>
                            <div class="chart-note">
                                <span class="dot dot--red"></span>
                                <span>Services</span>
                            </div>
                        </div>
                    </div>
                    <!-- END CHART PERCENT-->
                </div>
            </div>
        </div>
    </section>
    <!-- END STATISTIC CHART-->
</div>


@section scripts {

    <script>
        $(function () {
            
            try {
                var tabla = $('.table-top-campaign tbody');
                if (tabla) {
                    $.ajax({
                        method: 'GET',
                        url: '@Url.Action("obtenerVehiculos", "Graficas")',
                        dataType: "json",
                        success: function (data) {
                            $.each(data, function (i, item) {
                                var lugar = i + 1;
                                var fila = `
                                    <tr>
                                        <td>${lugar}. ${item.Marca}</td>
                                        <td>${item.cantidad}</td>
                                    </tr>
                                `;
                                tabla.append(fila);
                            })
                        }
                    });
                }
            } catch (error) {
                console.log(error);
            }

            try {

                // single bar chart
                var ctx = document.getElementById("singelBarChart");
                if (ctx) {
                    ctx.height = 200;
                    var visitas = [];
                    $.ajax({
                        method: 'GET',
                        async: false,
                        url: '@Url.Action("obtenerVisitas", "Graficas")',
                        dataType: "json",
                        success: function (data) {
                            visitas = data;
                        }
                    });
                    var myChart = new Chart(ctx, {
                        type: 'bar',
                        data: {
                            labels: ["Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"],
                            datasets: [
                                {
                                    label: "Cantidad de visitas",
                                    data: visitas,
                                    borderColor: "rgba(0, 123, 255, 0.9)",
                                    borderWidth: "0",
                                    backgroundColor: "rgba(0, 123, 255, 0.5)"
                                }
                            ]
                        },
                        options: {
                            legend: {
                                position: 'top',
                                labels: {
                                    fontFamily: 'Poppins'
                                }

                            },
                            scales: {
                                xAxes: [{
                                    ticks: {
                                        fontFamily: "Poppins"

                                    }
                                }],
                                yAxes: [{
                                    ticks: {
                                        beginAtZero: true,
                                        fontFamily: "Poppins"
                                    }
                                }]
                            }
                        }
                    });
                }

            } catch (error) {
                console.log(error);
            }
        })

    </script>

}